#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh

cp 0/alpha.liquid.org 0/alpha.liquid

runApplication setFields

runApplication decomposePar
# Get application directory
application=`getApplication`
runApplication mpirun -np 6 $application -parallel

runApplication reconstructPar


# ----------------------------------------------------------------- end-of-file
