#!/bin/bash

blockMesh > 1-blockMesh.log 2>&1
snappyHexMesh -overwrite > 2-snappyHexMesh.log 2>&1
extrudeMesh > 3-extrudeMesh.log 2>&1
rm 0/*
cp 0.org/* 0/
setFields > 4-setFields.log 2>&1
interFoam > 5-interFoam.log 2>&1