#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh

runApplication decomposePar

# Get application directory
application=`getApplication`

runApplication mpirun -np 4 -hostfile $PBS_NODEFILE $application -parallel

runApplication reconstructPar -latestTime

# ----------------------------------------------------------------- end-of-file