#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions


rm -rf proce*
rm -rf 0.*
rm -rf acousticData
rm -rf WallCoeff*

# ----------------------------------------------------------------- end-of-file
