#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

rm -rf constant/polyMesh
cp -rf constant/polyMesh0 constant/polyMesh

decomposePar | tee -a log.decomposePar
mpirun -np 60 -hostfile $PBS_NODEFILE rhoCentralFoam -parallel | tee -a log.rhoCentralFoam
reconstructPar -latestTime | tee -a log.reconstructPar

# ----------------------------------------------------------------- end-of-file