#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
foamClearPolyMesh

rm -f *.log
rm -f 0/*
rm -rf forceCoeffs